import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

const dm_sans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(dm_sans.className, 'antialiased')}>{children}</body>
    </html>
  );
}
